chore: introduce tsup for bundling
Added the package `tsup` to assist in bundling `@mswjs/source`-package so
it both supports CommonJS and ESM modules. The `package.json` file has
been modified so the appropriate properties for the modern `exports`-approach
of exporting, and the older `main`-`module` combination.

During building and running the tests the `fromOpenApi` had issues
to pass the tests or build due to the way the `SwaggerParser` utility
class was exporter. The code has been updated so it refers to
the `deferences`-function via `SwaggerParser.deferences()` instead of trying
to instantiate the class.

For this reason the `tsconfig.json` has been updated so that it enables
`esModuleInterop` and `allowSyntheticDefaultImports` after this change
the package build and bundled successfully with `tsup` and passed the
unit tests, before errors like below were shown:

    src/fromOpenApi/fromOpenApi.ts:16:35 - error TS2351: This expression is not constructable.
      Type 'typeof SwaggerParser' has no construct signatures.

    16   const specification = await new SwaggerParser().dereference(document)
                                         ~~~~~~~~~~~~~